version: '3.8'

services:
  # Selenium Hub
  selenium-hub:
    image: selenium/hub:4.16.1
    container_name: selenium-hub
    ports:
      - "4444:4444"
      - "4442:4442"
      - "4443:4443"
    environment:
      - GRID_MAX_SESSION=16
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    networks:
      - selenium-grid

  # Chrome Node
  chrome-node:
    image: selenium/node-chrome:4.16.1
    container_name: selenium-node-chrome
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5900:5900"
    networks:
      - selenium-grid
    volumes:
      - /dev/shm:/dev/shm

  # Firefox Node
  firefox-node:
    image: selenium/node-firefox:4.16.1
    container_name: selenium-node-firefox
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5901:5900"
    networks:
      - selenium-grid
    volumes:
      - /dev/shm:/dev/shm

  # Edge Node
  edge-node:
    image: selenium/node-edge:4.16.1
    container_name: selenium-node-edge
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=2
      - NODE_MAX_SESSION=2
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    ports:
      - "5902:5900"
    networks:
      - selenium-grid
    volumes:
      - /dev/shm:/dev/shm

  # Allure Report Server
  allure-server:
    image: frankescobar/allure-docker-service:2.24.0
    container_name: allure-server
    ports:
      - "5050:5050"
    environment:
      - CHECK_RESULTS_EVERY_SECONDS=3
      - KEEP_HISTORY=20
      - KEEP_HISTORY_LATEST=10
    volumes:
      - ./reports/allure-results:/app/allure-results
      - ./reports/allure-report:/app/default-reports
    networks:
      - selenium-grid

  # Test Runner Service (Optional - for CI/CD)
  test-runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-runner
    depends_on:
      - selenium-hub
      - chrome-node
      - firefox-node
    environment:
      - REMOTE_EXECUTION=true
      - HUB_URL=http://selenium-hub:4444/wd/hub
      - BROWSER=chrome
      - ENVIRONMENT=test
    volumes:
      - ./reports:/app/reports
      - ./src:/app/src
      - ./testng.xml:/app/testng.xml
      - ./pom.xml:/app/pom.xml
    networks:
      - selenium-grid
    profiles:
      - ci

networks:
  selenium-grid:
    driver: bridge

volumes:
  allure-results:
  allure-reports: